version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: The First Step
         command: |
           echo 'Hello World Mrigank!'
     - run:
         name: Code Has Arrived
         command: |
           ls -al
           echo "------Here----"
     - run:
         name: Running in a Unique Container
         command: |
           node -v
